CREATE TABLE IF NOT EXISTS vets
(
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT,
  last_name  TEXT
);
CREATE INDEX ON vets (last_name);
COMMENT ON TABLE vets IS '수의사';

CREATE TABLE IF NOT EXISTS specialties
(
  id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT
);
CREATE INDEX ON specialties (name);
COMMENT ON TABLE specialties IS '전문분야';

CREATE TABLE IF NOT EXISTS vet_specialties
(
  vet_id       INT NOT NULL REFERENCES vets (id),
  specialty_id INT NOT NULL REFERENCES specialties (id),
  UNIQUE (vet_id, specialty_id)
);
COMMENT ON TABLE vet_specialties IS '수의사 전문분야 매핑';

CREATE TABLE IF NOT EXISTS types
(
  id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT
);
CREATE INDEX ON types (name);
COMMENT ON TABLE types IS '펫 종류';

CREATE TABLE IF NOT EXISTS owners
(
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT,
  last_name  TEXT,
  address    TEXT,
  city       TEXT,
  telephone  TEXT
);
CREATE INDEX ON owners (last_name);
COMMENT ON TABLE owners IS '펫 주인';

CREATE TABLE IF NOT EXISTS pets
(
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT,
  birth_date DATE,
  type_id    INT NOT NULL REFERENCES types (id),
  owner_id   INT REFERENCES owners (id)
);
CREATE INDEX ON pets (name);
CREATE INDEX ON pets (owner_id);
COMMENT ON TABLE pets IS '펫';

CREATE TABLE IF NOT EXISTS visits
(
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_id      INT REFERENCES pets (id),
  visit_date  DATE,
  description TEXT
);
CREATE INDEX ON visits (pet_id);
COMMENT ON TABLE visits IS '펫 방문 기록';

